feat: add manual-revocation-check script
mattrglobal/sample-apps pull request #177
Opened 2024-10-09 22:38 UTC by raleng

# Description

This adds a script to demonstrate how to retrieve the revocation list from the public endpoint, how to decode the list, and how to check the credential status.

For convenience, this also let's you pass an encoded compact or compact-semantic credential. The script will decode the credential to retrieve the revocation list URL and index.

2024-10-18 02:49 UTC, avner-m requested changes

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +MATTR provides capabilities to issue revokable credentials, to manage the revocation status of credentials, and to check the revocation status of a credential. Check out our [Credential Management](h
```suggestion
MATTR provides capabilities to issue revokable credentials, to manage the revocation status of credentials, and to check the revocation status of a credential. Check out our [credential management](https://learn.mattr.global/docs/capabilities/management) capabilities and our [Revocation tutorial](https://learn.mattr.global/tutorials/management/revocation) to learn more.
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +While we highly suggest to leverage your MATTR tenant for credential management, credentials also include the necessary information to check their revocation status manually to enable interoperabilit
```suggestion
While we highly recommend to leverage your MATTR tenant for credential management, credentials also enable unauthenticated relaying parties to check their revocation status to enable interoperability.
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +### Web Semantic Credentials
```suggestion
### JSON credentials
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +Web Semantic credentials contain a `credentialStatus` field that holds the reference to a revocation list.
```suggestion
JSON credentials contain a `credentialStatus` field that holds the reference to a revocation list.
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +### Compact and Compact-Semantic Credentials
```suggestion
### CWT and semantic CWT credentials
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +Compact and compact-semantic credentials are usually shared and verified in their encoded forms. For convenience, you can provide the encoded credential or the revocation list URL and index to the sc
```suggestion
CWT and Semantic CWT credentials are usually shared and verified in their encoded forms. For convenience, you can provide the encoded credential or the revocation list URL and index to the script.
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +If you provide the encoded compact credential, the script will decode the credential and retrieve the list URL and index.
```suggestion
If you provide the encoded form, the script will decode the credential and retrieve the list URL and index.
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
> +If you decode the compact credential yourself, you can pass the revocation list URL and index.
```suggestion
If you decode the credential yourself, you can pass the revocation list URL and index.
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/manual-revocation-check.js
> +// Compact Credentials are base32 encoded CBOR web tokens
```suggestion
// CWT credentials are base32 encoded CBOR web tokens
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/manual-revocation-check.js
> +// Revocable compact credentials contain a reference to the
```suggestion
// Revocable CWT credentials contain a reference to the
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/manual-revocation-check.js
> +// The public revocation list endpoint for compact credentials
```suggestion
// The public revocation list endpoint for CWT credentials
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/manual-revocation-check.js
> +// The public revocation list endpoint for web semantic credentials
```suggestion
// The public revocation list endpoint for JSON credentials
```

2024-10-18 02:49 UTC, avner-m commented on manual-revocation-check/README.md
Do you think we could/should add an example credential of each type for them to play with?

Also do we want to show what the result of that script looks like or explain what it actually does?

2024-10-23 00:48 UTC, raleng commented on manual-revocation-check/README.md
> +While we highly suggest to leverage your MATTR tenant for credential management, credentials also include the necessary information to check their revocation status manually to enable interoperabilit
```suggestion
While we highly recommend to leverage your MATTR tenant for credential management, credentials also enable unauthenticated relying parties to check their revocation status to enable interoperability.
```

2024-10-23 01:22 UTC, raleng commented on manual-revocation-check/README.md
A JSON credential example is basically there already (though we only share the `credentialStatus` object, not the whole credential). We certainly can add a compact credential as well.

The output is just text in the terminal, but I can add a section to give a sample output.

2024-10-29 19:12 UTC, preetpatel approved these changes

2024-10-29 20:14 UTC, avner-m commented on manual-revocation-check/README.md
> +### CWT and semantic CWT credentials
```suggestion
### CWT and Semantic CWT credentials
```

2024-10-29 20:15 UTC, avner-m approved these changes

2024-10-29 20:23 UTC, merged